version: '3'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=API
      - DB_PASSWORD=azerty
      - DB_NAME=library

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: azerty
      MYSQL_DATABASE: liberary
      MYSQL_USER: API
      MYSQL_PASSWORD: azerty
    ports:
      - "3307:3306"
